### ISSUE TITLE
django-fast-update usage

### ISSUE THREAD

**Issue by jerch** [danjac/radiofeed-app#213]
Just a minor headsup from my side regarding `django-fast-update` - `fast_update` can normally deal with much bigger batch sizes than `bulk_update`. If you are not restricted by other means (e.g. running out of memory) you could try batch sizes in the 10k - 100k ballpark, which should give a much higher perf bonus (50-80x faster) than a batch size of 100 (10-15x faster, all compared to `bulk_update`).

And since your code looks like you are seeking high perf in general - you even might want to try `copy_update` (assuming you are on postgres), which is 2x faster than `fast_update` around 1k records up to 4 times for +100k records. (While `copy_update` is labelled as alpha, it is fully tested against django standard field types. It should just work, if you dont use any exotic 3rd party or self declared field types.)

**Comment by danjac** [comment]
That's really good advice, thank you.
